#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080
export HTTP_CLIENT="wget --no-check-certificate -O"
export PORT=$OPENSHIFT_DIY_PORT
export HOST=$OPENSHIFT_DIY_IP
export HOME=$OPENSHIFT_DATA_DIR
export LEIN_JVM_OPTS=-Duser.home=$HOME

# Makesure leinigen exist
if [ ! -e $OPENSHIFT_DATA_DIR/bin/lein ]; then
    mkdir -p $OPENSHIFT_DATA_DIR/bin
    wget -O $OPENSHIFT_DATA_DIR/bin/lein https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
    chmod +x $OPENSHIFT_DATA_DIR/bin/lein
fi

# Make sure we are on root folder of project
cd $OPENSHIFT_REPO_DIR

# Fetch deps
$OPENSHIFT_DATA_DIR/bin/lein deps

# Migrate database or create it
$OPENSHIFT_DATA_DIR/bin/lein run -- migrate

# Start the aplication
nohup $OPENSHIFT_REPO_DIR/bin/lein trampoline run 2>&1 | /usr/bin/logshifter -tag clojuretwbot &
