language: clojure
sudo: false
jdk:
  - oraclejdk8
  - oraclejdk7
before_install:
  - mkdir ~/bin
  - wget https://raw.github.com/technomancy/leiningen/stable/bin/lein -P ~/bin/
  - chmod a+x ~/bin/lein
lein: ~/bin/lein
script:
  - lein test
