language: clojure
sudo: false
env:
  global:
  - GH_REF: github.com/clojure-tw/telegram-bot-clojuretwbot
jdk:
  - oraclejdk8
  - oraclejdk7
before_install:
  - mkdir ~/bin
  - wget https://raw.github.com/technomancy/leiningen/stable/bin/lein -P ~/bin/
  - chmod a+x ~/bin/lein
lein: ~/bin/lein
script:
  - lein marg
